# Generated by Django 5.1.5 on 2025-01-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
            ],
            options={
                "verbose_name": "Завод",
                "verbose_name_plural": "Заводы",
            },
        ),
        migrations.CreateModel(
            name="Individual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "debt",
                    models.FloatField(
                        default=0, verbose_name="Задолженность перед поставщиком"
                    ),
                ),
            ],
            options={
                "verbose_name": "Индивидуальный предприниматель",
                "verbose_name_plural": "Индивидуальные предприниматели",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название продукта",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "model_product",
                    models.CharField(
                        blank=True,
                        help_text="Укажите модель продукта",
                        max_length=255,
                        null=True,
                        verbose_name="Модель",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату выхода на рынок",
                        null=True,
                        verbose_name="Дата выхода",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="Retail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "debt",
                    models.FloatField(
                        default=0, verbose_name="Задолженность перед поставщиком"
                    ),
                ),
            ],
            options={
                "verbose_name": "Розничная сеть",
                "verbose_name_plural": "Розничные сети",
            },
        ),
    ]
