# Generated by Django 5.1.5 on 2025-01-17 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ecomerc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="factory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_factory",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Завод",
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="supplier",
            field=models.ForeignKey(
                help_text="Укажите поставщика",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Поставщик",
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_individual",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Завод",
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecomerc.product",
                verbose_name="Продукты",
            ),
        ),
        migrations.AddField(
            model_name="factory",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecomerc.product",
                verbose_name="Продукты",
            ),
        ),
        migrations.AddField(
            model_name="retail",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecomerc.product",
                verbose_name="Продукты",
            ),
        ),
        migrations.AddField(
            model_name="retail",
            name="supplier",
            field=models.ForeignKey(
                help_text="Укажите поставщика",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Поставщик",
            ),
        ),
        migrations.AddField(
            model_name="retail",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_retail",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Завод",
            ),
        ),
    ]
