# Generated by Django 5.1.5 on 2025-01-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomerc", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Добавьте описание продукта",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Отметьте если в продаже",
                verbose_name="В продаже",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.FloatField(
                default=0, help_text="Укажите стоимость", verbose_name="Цена"
            ),
        ),
    ]
