# Generated by Django 5.1.5 on 2025-01-18 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomerc", "0003_product_description_product_is_published_and_more"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individual",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
                verbose_name="Продукты",
            ),
        ),
        migrations.AlterField(
            model_name="retail",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
                verbose_name="Продукты",
            ),
        ),
        migrations.AlterField(
            model_name="factory",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
                verbose_name="Продукты",
            ),
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
