# Generated by Django 5.1.5 on 2025-01-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название продукта",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "model_product",
                    models.CharField(
                        blank=True,
                        help_text="Укажите модель продукта",
                        max_length=255,
                        null=True,
                        verbose_name="Модель",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Добавьте описание продукта",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        default=0, help_text="Укажите стоимость", verbose_name="Цена"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте если в продаже",
                        verbose_name="В продаже",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату выхода на рынок",
                        null=True,
                        verbose_name="Дата выхода",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
