# Generated by Django 5.1.5 on 2025-01-18 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите доступное количество",
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="user",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="Завод"
            ),
        ),
    ]
