# Generated by Django 5.1.5 on 2025-01-19 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_remove_warehouse_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="warehouse",
            options={
                "verbose_name": "Продукт на склад",
                "verbose_name_plural": "Продукты на Складе",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="user",
            field=models.ManyToManyField(
                related_name="user_product",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Производитель",
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_warehouse",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Поставщик",
            ),
        ),
    ]
