# Generated by Django 5.1.5 on 2025-01-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_warehouse_options_alter_product_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото",
                null=True,
                upload_to="products/avatars/",
                verbose_name="Фото",
            ),
        ),
    ]
