# Generated by Django 5.1.5 on 2025-01-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_product_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото",
                null=True,
                upload_to="products/photo/",
                verbose_name="Фото",
            ),
        ),
    ]
